### ISSUE TITLE
Bitmovin 8.8 fails with HLS or MPEG-DASH streams

### ISSUE THREAD

**Issue by maniland** [bitmovin/bitmovin-player-webos-demo#3]
I have set up a basic app using the example contained within. using our default dash and has content with has been packaged using the Unified Streaming Packager.

I am getting Decoding errors for non-DRM'd content the url's are below

this is via the emulator, which I'd expect errors if using DRM'd content but should work with non-DRM'd

https://d1chyo78gdexn4.cloudfront.net/vualto-demo/sintel/sintel_nodrm.ism/manifest.mpd
https://d1chyo78gdexn4.cloudfront.net/vualto-demo/sintel/sintel_nodrm.ism/manifest.m3u8

**Comment by dweinber** [comment]
This doesn't seem to be related to this demo app. If you have any questions or issues with this SDK or its examples, or you require other technical support for our services, please log in to your Bitmovin Dashboard at https://bitmovin.com/dashboard and [create a new support case](https://bitmovin.com/dashboard/support/cases/create). Our team will get back to you as soon as possible :+1:
